// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4IDVHtWUXi-9c_y3ysOu7AwJ8m1Cytr0',
    appId: '1:186920755881:web:6e573fa9bdab62980dffb8',
    messagingSenderId: '186920755881',
    projectId: 'smartnotes-15d14',
    authDomain: 'smartnotes-15d14.firebaseapp.com',
    storageBucket: 'smartnotes-15d14.firebasestorage.app',
    measurementId: 'G-3CCC9T95PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptYTrpRStK4gR2pBYhCcDCKse0r7VPcQ',
    appId: '1:186920755881:android:5e94ffcbe2e827040dffb8',
    messagingSenderId: '186920755881',
    projectId: 'smartnotes-15d14',
    storageBucket: 'smartnotes-15d14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEg2bL3DrjOQME-0ABKfZKJeusP4nX0k',
    appId: '1:186920755881:ios:1855ec233373d1d40dffb8',
    messagingSenderId: '186920755881',
    projectId: 'smartnotes-15d14',
    storageBucket: 'smartnotes-15d14.firebasestorage.app',
    iosBundleId: 'com.example.smartnotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEg2bL3DrjOQME-0ABKfZKJeusP4nX0k',
    appId: '1:186920755881:ios:1855ec233373d1d40dffb8',
    messagingSenderId: '186920755881',
    projectId: 'smartnotes-15d14',
    storageBucket: 'smartnotes-15d14.firebasestorage.app',
    iosBundleId: 'com.example.smartnotesApp',
  );
}
